In [9]:
import numpy as np
from utils import create_window, split_train_test

In [10]:
WINDOW_SIZE = 4

In [11]:
data = np.load("cloud.npz", encoding="latin1", allow_pickle=True)
train = data["train"]

In [12]:
def create_window(input_data: np.array, step_size: int) -> np.array:
    data_len = len(input_data)
    result = np.zeros((data_len-step_size+1, step_size, *input_data.shape[1:]))
    for i in range(data_len):
        if i+step_size <= data_len:
            result[i] = input_data[i:i+step_size]
    return result

In [20]:
x, y = split_train_test(create_window(xxx, 3))

In [26]:
a = create_window(train[0], 5)
b = create_window(train[1], 5)
np.vstack((b, a)).shape

(107, 5, 3)

In [31]:
x = np.zeros((0,WINDOW_SIZE, 3))
for i, sample in enumerate(train):
    x = np.vstack((x,create_window(sample, WINDOW_SIZE)))
    
    if 1 % 100 == 0:
        print(f")

In [45]:
xxx = np.arange(11) +1
xxx

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [48]:
create_window(xxx, 5)

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 2.,  3.,  4.,  5.,  6.],
       [ 3.,  4.,  5.,  6.,  7.],
       [ 4.,  5.,  6.,  7.,  8.],
       [ 5.,  6.,  7.,  8.,  9.],
       [ 6.,  7.,  8.,  9., 10.],
       [ 7.,  8.,  9., 10., 11.]])

In [71]:
def add(x, y):
    return x + ynp.arange(100).reshape((10,10))

In [57]:
a = (3, 4)

In [70]:
np.arange(100).reshape((10,10))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])