In [8]:
import numpy as np

from utils import create_window, split_train_test

In [2]:
x = np.arange(100)
y = np.arange(100)

In [3]:
create_window([2,3,4,5,6,2,3,5], 3)

array([[2., 3., 4.],
       [3., 4., 5.],
       [4., 5., 6.],
       [5., 6., 2.],
       [6., 2., 3.],
       [2., 3., 5.]])

In [4]:
windows = create_window(np.arange(1000), 10)

In [5]:
windows

array([[  0.,   1.,   2., ...,   7.,   8.,   9.],
       [  1.,   2.,   3., ...,   8.,   9.,  10.],
       [  2.,   3.,   4., ...,   9.,  10.,  11.],
       ...,
       [988., 989., 990., ..., 995., 996., 997.],
       [989., 990., 991., ..., 996., 997., 998.],
       [990., 991., 992., ..., 997., 998., 999.]])

In [6]:
x, y  = split_train_test(windows)

In [7]:
x

array([[  0.,   1.,   2., ...,   6.,   7.,   8.],
       [  1.,   2.,   3., ...,   7.,   8.,   9.],
       [  2.,   3.,   4., ...,   8.,   9.,  10.],
       ...,
       [988., 989., 990., ..., 994., 995., 996.],
       [989., 990., 991., ..., 995., 996., 997.],
       [990., 991., 992., ..., 996., 997., 998.]])